name: legend_core
description: Core modular architecture for dependency injection, routing, and module lifecycle in Flutter apps.
version: 0.1.0
publish_to: "none"

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.2
  get_it: ^9.2.1
  logger: ^2.7.0

